### ISSUE TITLE
Help with options 

### ISSUE THREAD

**Issue by nam-co** [yoelpc4/laravel-cloudinary#1]
Hi Yoel, thanks for the work on this cool package, Im just starting with Cloudinary and I was wondering how can I specify transformation when uploading files:
For example in this: Storage::disk('cloudinary')->put($path.$filename, $img->__toString(), 'public'); 
where can I put: 
array("gravity"=>"face", "height"=>150, "width"=>150, "crop"=>"thumb")

Appreciate any help, thanks

**Comment by yoelpc4** [comment]
Sorry for super late reply @nam-co, tbh I never do any transformation to the image on cloudinary.

This package is intended to be a cloudinary adapter with [illuminate/filesystem](https://github.com/illuminate/filesystem) and [league/flysystem](https://github.com/thephpleague/flysystem), so any functionalities beyond these packages aren't supported at this time.

I suggests you to use [spatie/image](https://github.com/spatie/image) package for image manipulation, then store the result to the cloudinary as usual.
