### ISSUE TITLE
Unable to list contents from location:

### ISSUE THREAD

**Issue by segunemma2003** [yoelpc4/laravel-cloudinary#11]
Unable to list contents from location: livewire-tmp. Rate Limit Exceeded. Limit of 500 api operations reached. Try again on 2024-10-04 14:00:00 UTC
i get this error after making some uploads

**Comment by yoelpc4** [comment]
Hi @segunemma2003 your issue might be caused of your admin API requests exceeds free plan rate limit, to solve it you have to try one of these solution:
1. Switch to paid plan which give you 2000 requests per hour
2. Retry after the given timestamp on error message

You can read more about it here: 
https://cloudinary.com/glossary/rate-limit
https://support.cloudinary.com/hc/en-us/articles/202520892-Are-Cloudinary-APIs-rate-limited
