### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by rezuankassim** [yoelpc4/laravel-cloudinary#2]
is there any update to support Laravel 9?

**Comment by yoelpc4** [comment]
Looks likely I need more time to support laravel 9 because it uses league/flysystem v3.0.0 while laravel 8 uses league/flysystem v1.1.9

**Comment by yoelpc4** [comment]
Here is the [support](https://github.com/yoelpc4/laravel-cloudinary/releases/tag/v3.0.0) for laravel 9 @rezuankassim

**Comment by rezuankassim** [comment]
Thank you very much @yoelpc4 !
