### ISSUE TITLE
Undefined Array Key

### ISSUE THREAD

**Issue by xfkrahmad** [yoelpc4/laravel-cloudinary#5]
![Screenshot_85](https://user-images.githubusercontent.com/71373710/201459897-c8a16427-3d73-4d79-8801-3d0c8ba18990.png)
did i miss some step? thank you

**Comment by yoelpc4** [comment]
Hi @xfkrahmad,

Make sure fill in the `CLOUDINARY_CLOUD_NAME` value on your .env file, also please check the [Environment Variable section on package readme](https://github.com/yoelpc4/laravel-cloudinary#environment-variable) if you need help.
