### ISSUE TITLE
Undefined array key "cloud_name"

### ISSUE THREAD

**Issue by agumaxwellforcode** [yoelpc4/laravel-cloudinary#7]
Using 

 Storage::disk('cloudinary')->put("test.png", $file);
 
 
<img width="725" alt="image" src="https://github.com/yoelpc4/laravel-cloudinary/assets/39837742/340e8ef1-f6fb-4a04-9bdf-d152cfab8356">

**Comment by yoelpc4** [comment]
@agumaxwellforcode  Could you show your `.env` file?

**Comment by yoelpc4** [comment]
@agumaxwellforcode I've tried to fresh install laravel project with setup following the readme resulted in able to upload
<img width="1085" alt="Screenshot 2023-11-01 at 00 47 40" src="https://github.com/yoelpc4/laravel-cloudinary/assets/31505544/8b4d7a0c-38ef-412a-a75e-8417c9a71c4f">
