### ISSUE TITLE
Laravel 11 support?

### ISSUE THREAD

**Issue by henryonsoftware** [yoelpc4/laravel-cloudinary#9]
I check and see we haven't supported Lar 11 yet. Will we support it soon?

**Comment by yoelpc4** [comment]
Hi @henryonsoftware @valerius21 pardon me for slow response because I was busy with work 🙏🏻, I just added support to Laravel 11. Please check [v5.0.0 release](https://github.com/yoelpc4/laravel-cloudinary/releases/tag/v5.0.0) for more details, thank you for requesting it.
